### ISSUE TITLE
Downloading TikTok user channel problem

### ISSUE THREAD

**Issue by outshrill** [haruhi-dl/haruhi-dl#8]
When I try to download a tiktok complete user, videos between number 30 and 70 (sometimes other aprox range but always between 30 and 70) are always marked as "has already been downloaded". I tried different channels and it is always the same.

haruhi-dl --version 2021.04.01
Pop!_OS 20.10

Here the output and the -v [ouput.txt](https://github.com/haruhi-dl/haruhi-dl/files/6526310/ouput.txt)

**Comment by selfisekai** [comment]
Hi, it seems like TikTok returns duplicated videos on the user page [@physics.world](https://tiktok.com/@physics.world) (this user has just 45 videos), though some like [@puczirajot](https://tiktok.com/@puczirajot) don't for me. Anyway, this seems to be fixed by the commit 2c8fa6, which will be included in the next release. Thanks for reporting the issue.
